import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { languages } from '../i18n/settings'
import { getT } from '../i18n'
import  ThemeProvider  from "../context/ThemeContext";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Madiavo",
//   description: "Generated by create next app",
// };

export async function generateMetadata() {
  const { t } = await getT('second-page')
  return {
    title: t('Madiavo'),
    description: t('Generated by create next app'),
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
